### ISSUE TITLE
Shouldn't assume card$i always comes with hwmon$i

### ISSUE THREAD

**Issue by Jimmy-Z** [Shaped/amdpwrman#1] opened 2021-02-21 18:19 UTC
On my system I have `/sys/class/drm/card0/device/hwmon/hwmon1` and `/sys/class/drm/card1/device/hwmon/hwmon2`.

I wrote a smaller script for my personal use:
https://gist.github.com/Jimmy-Z/6d481a6b6ec9843fb1b1a3a86f0e51ad

**Comment by Gillicutti** [comment] 2021-10-11 19:33
Hi!

New to Linux and trying not to fry my RX 580.

I have no idea how to run these scripts. I just know that I love that there's an ability to set a fan curve and therefore solve my issue.

I am at 5000 ft altitude so I need the extra air flow but so far am having a heck of a time finding anything that works. It seems everything is abandoned projects and partial command sets like unfinished sentences someone is actually speaking.

If it's possible I'd love to know more on how to execute these scripts and worth noting the stuff about hwmon shouldn't be assumed. You're right. Ubuntu 21.04 and I've been looking for it in the synapic package thing and tried to call it directly but nothing. Not sure if you can call it directly with a sudo but I tried anyway.

Point is, you all got something that looks like it works and it won't freak out python either (yeah another unfinished project has an issue with python when run that makes it not work).

There was a reddit about amdpwrman and that's how i found this. The author noted how there's a lot of interest in this. Yes there is because AMD is really bad about updates and doesn't really listen to users (a friend of mine works at a fortune 500 company, does the whole quarterly thing with the execs and is a big deal in their IT department and AMD's recent drivers created problems, they wouldn't even give him the time of day). So what you're doing here is important because it is the difference in us keeping our graphics cards and enjoying them versus our needing to buy new ones that, as prices and availability are real issues right now with chip shortages and all that, cards like mine that once sold for $200 are now $1000. I can't replace what I have easily, and doubt many can. So thank you for working on this in the first place and hope you can find a way to finish this project. If it's not prohibited by Github I'd make sure people know where to send donations too.

I know you did this for managing multiple cards to do the whole coin searching thing but know that what you did is really needed by many of us for a lot of other reasons. It's a genuine good deed that may lead places where you are creating whole new coins for whole new economies and to fund whatever they're about.

Thank you both for your time.

**Comment by Jimmy-Z** [comment] 2021-10-12 07:19
They are shell scripts not python, for AMD GPUs I'd suggest using Team Red Miner's built-in fan control, it supports target temperature control, way better than curve, unfortunately one of my GPUs is not supported by TRM so I had to resort to this.

BTW I'm not affiliated with TRM.

**Comment by ForbiddenEra** [comment] 2021-11-13 19:54
Didn't see this issue. Didn't think anyone was even using it, but glad someone found some use.

Hm, I'm not sure how to heuristic your situation; I haven't seen that even with other GPUs installed but I suppose once you're within /card*/, any hwmon* should be fine..

There were a few bugs I did find though, not sure if I posted an update since I fixed those either, perhaps I'll push an update soon.

**Comment by ForbiddenEra** [comment] 2021-12-04 05:12
So, I have come across this issue now with my test rig by adding an NV card and occasionally the system boots with things swapped around. I don't know when I'll have time to fix it but I'll definitely give it a shot when I can.

**Comment by ForbiddenEra** [comment] 2021-12-04 05:18
I should note that I'm also considering re-writing it in something other than shell script, but I want something that doesn't have heavy dependencies.

My next choice would be NodeJS but not everyone has this installed, though it could run as a service pretty slick like that.

I don't like python and again same issue plus it seems python dependencies can be hell, just using other python stuff before myself and setting up venvs and stuff has been a headache.

Perl would be a great solution as most Linux distro's have it OOB still these days but it's not 2001 and I don't think I've touched perl since.

Keeping it shell definitely limits some things and makes it harder to maintain but having bash and the amdgpu drivers as the only dependencies is wicked. Tough choice.

After reading your post again, thanks for the kind comments, I'd also like to point out that the script only uses exposed 'files' on the sys filesystem to do it's work, it was just meant to make it easier to type something like 'amdpwrman fan enable 0' rather than 'echo 1 > /sys/class/drm/card0/device/blah/blah' - I guess you've gotten that since you've made your own script.

The fancurve functionality isn't/wasn't finished; the plan was to have it run as a daemon and constantly set speeds based on a curve that you can set. I'd rather not make a shell script a daemon which is why I didn't finish that part, again, I'm a bit torn on how to continue. Node, again would be my choice but a lot of distro's, especially LTS, come with an old version of nodeJS .. not too difficult to install a newer one, but again, dependencies...

Perhaps an idea is to make the fancurve daemon in nodejs, but keep the script as is and then the dependency is only required for fancurve usage. Not sure.

I generally just crank the fans or turn them off depending on my needs but I suppose it would be a good feature to finish.

My system doesn't boot everytime with the cards in an odd order unfortunately, so while I have reproduced it, currently it's in correct order on this boot :(

**Comment by ForbiddenEra** [comment] 2021-12-04 05:37
Okay, I've pushed a fix that should fix this issue. I haven't been able to test fully for when the cards don't match up, but now instead of assuming hwmon${x} is GPU${x}, it looks inside GPU${x}'s hwmon folder to find the actual name it should use and uses that.

Let me know if it works for you and I can close the issue.

**Comment by ForbiddenEra** [comment] 2021-12-08 00:32
My original fix for this issue sort of introduced another issue; the hwmon variable - which is now created by actually looking in the directory for the appropriate folder instead of assuming it based on GPU# - wasn't being set in every function as it should've been, causing every function except `show` to break.

Fortunately someone pointed this out in #2 - although I would've realized as soon as I did try to change settings on one of my GPUs, I'm not sure _when_ that would've been - so this definitely got fixed quicker because of it.

This issue should be resolved now, so I'm going to close this.

**Closed as completed by ForbiddenEra** 2021-12-08 00:32 UTC
